name: Publish
on: [push]
concurrency: ci-${{ github.ref }}
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - uses: gradle/wrapper-validation-action@v1

      - name: Build and publish locally to folder
        run: ./gradlew build javadocJar checkVersion publish --stacktrace

      - name: Clone aabric-libraries repo
        uses: actions/checkout@v4
        with:
          repository: floofyplasma/aabric-libraries
          token: ${{ secrets.WORKFLOW_TOKEN }}
          path: aabric-libraries

      - name: Copy published artifacts to repo
        run: |
          cp -r build/dist/* aabric-libraries/

      - name: Commit and push changes
        run: |
          cd aabric-libraries
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update published artifacts from ${{ github.sha }}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
